# Generated by Django 5.1.15 on 2026-04-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("genre", models.CharField(db_index=True, max_length=100)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                (
                    "publication_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="authors.author",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
                    models.Index(
                        fields=["title", "genre"], name="books_book_title_75188e_idx"
                    ),
                ],
            },
        ),
    ]
